language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "pip install -e git://github.com/edx/xblock-sdk.git#egg=xblock-sdk"
    - "pip install -r requirements.txt"
    - "pip install -r test-requirements.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements.txt"
    - "python setup.py sdist && pip install dist/xblock-group-project-v2-0.3.tar.gz"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/test-requirements.txt"
script:
    - pep8 group_project_v2 tests --max-line-length=120
    - pylint group_project_v2 tests --rcfile=pylintrc
    - python run_tests.py --with-coverage --cover-package=group_project_v2
notifications:
  email: false
addons:
  firefox: "36.0"
